FROM node:20-alpine

# Install nodemon globally
RUN npm install -g nodemon

# Set working directory
WORKDIR /app

# Copy package files and install all dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the source code
COPY . .

# Set environment
ENV NODE_ENV=development

# Expose app port
EXPOSE 5050

# Use nodemon to watch for file changes
CMD ["npm", "run", "dev"]
